[functions.invite-user]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.sync-contratos-comprasnet]
verify_jwt = false

[functions.gerar-termo-referencia-compras]
verify_jwt = false
